#.github/workflows/sit-workflow.yml
name: Automatic deploy release to SIT
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Salesforce
    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history commit
          fetch-depth: 0
    
      - name: 'Update Latest Node'
        uses: actions/setup-node@v3
        with:
          node-version: '>=16'
          check-latest: true

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          echo y | sf plugins install sfdx-git-delta

      # Git Fetch
      - name: Git Fetch
        run: |
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all

      # generate DIFF package
      - name: Generate DIFF Package
        run: |
          git checkout -b pr 
          sf sgd source delta --to pr --from origin/merge --ignore .gitignore --output .  

      # Display Package XML
      - name: Display Package XML
        run: 'cat package/package.xml'

      # Echo Salesforce confg
      - name: Check Salesforce CLI config
        run: 'sf config list'

      # Convert Source format to Metadata format
      - name: Convert DIFF package to Metadata
        run: 'sf project convert source -x package/package.xml -d convert'  

      # Check if Apex is present in package
      - name: Check for Apex in package
        id: check_apex
        run: |
          if grep -qE "<name>ApexClass</name>|<name>ApexTrigger</name>" package/package.xml; then
            echo "apex_present=true" >> $GITHUB_OUTPUT
          else
            echo "apex_present=false" >> $GITHUB_OUTPUT
          fi
      
      # Store secret for DEVTMA hub
      - name: 'Populate auth file with SF_AUTH_URL secret'
        shell: bash
        run: 'echo ${{ secrets.SF_AUTH_URL}} > ./SF_AUTH_URL.txt'
      
      # Authenticate DEVTMA ORG
      - name: 'Authenticate SIT ORG'
        run: 'sf org login sfdx-url -f ./SF_AUTH_URL.txt -a devorg -d'
      
      # Deploy delta package
      - name: Deploy DIFF package
        run: 'sf project deploy start --metadata-dir convert --test-level RunLocalTests -w 60 -o sitorg --verbose'
      
      # Deploy delta package
      #- name: Deploy DIFF package
        #run: |
          #if [ "${{ steps.check_apex.outputs.apex_present }}" = "true" ]; then
            #echo "Apex found → Running tests"
            #sf project deploy start --metadata-dir convert --test-level NoTestRun -w 60 -o sitorg --verbose
          #else
            #echo "No Apex → Skipping tests"
            #sf project deploy start --metadata-dir convert --test-level NoTestRun -w 60 -o sitorg --verbose
          #fi